---
- name: "Apache installation using docker"
  hosts: prod
  become: true
  pre_tasks:
    - name: download pip script
      get_url:
        url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
        dest: /tmp/get-pip.py

    - name: install python-pip
      command: python2.7 /tmp/get-pip.py

    - name: Install docker python
      pip: name=docker-py
  tasks:
    - name: Template a file to /etc/files.conf
      template:
        src: /home/admin/webapp-ansible-apache/templates/index.html.j2
        dest: /etc/index.html
    - name: Create Apache container
      docker_container:
        name: webapp
        image: httpd
        ports:
          - "80:80"
        volumes:
        - /etc/index.html:/usr/local/apache2/htdocs/index.html
